[general]
import = [ "~/.config/alacritty/themes/catppuccin-frappe.toml" ]

[cursor]
vi_mode_style = "Underline"

[cursor.style]
blinking = "Always"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "monospace"
style = "Bold"

[font.glyph_offset]
y = 0

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[font.offset]
x = 0
y = 0

[scrolling]
history = 1000
multiplier = 3

[window]
decorations = "none"
opacity = 1

[window.dimensions]
columns = 80
lines = 35

[window.padding]
x = 0
y = 0
